<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AssemblyName>ZapretByGrubeer.Core</AssemblyName>
    <RootNamespace>Zapret.Core</RootNamespace>
    <FileDescription>Запрет by Grubeer — core</FileDescription>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="8.0.1" />
  </ItemGroup>

</Project>
